### ISSUE TITLE
[Bug] Can't close dashboard

### ISSUE THREAD

**Issue by exiva** [peterhajas/MobileNotifier#228] opened 2011-05-29 19:41 UTC
In Beta5 if you are using a activator action to display the dashboard (For example, if you're on an old 3g and don't have/want Backgrounding) you can't close the display. Clicking home doesn't close it, and the only way to do it is to clear all notifications.

**Comment by marshallford** [comment] 2011-05-30 02:03
Yes, this is my only issue....

And please support textfree.

ipt 4.2.1

**Comment by marshallford** [comment] 2011-05-30 03:28
Here's an idea...

IF: not in app switcher & in dashboard

THEN: when user taps home button
hide dashboard

ELSE:
Stop

**Comment by timbob1907** [comment] 2011-05-30 15:40
I've also encountered this

**Comment by marshallford** [comment] 2011-05-30 19:20
Quick Fix!

I created a dummy app in the root applications folder.
Then I made it hide the status bar to make it look pretty.
Next I assigned the short lock hold to the newly made app in activator, and the swipe down on status bar to to "show dash".

You see, the dash closes whenever an app opens, so I just made an app that crashes in like a 1/4 of a second, but forces the dash to close.

Good luck!

**Comment by Drudoo** [comment] 2011-05-31 12:22
I am trying to fix this. It is a problem for me too. So far i am testing a touch on the background will close the dashboard. It is not working right now.

**Comment by exiva** [comment] 2011-06-01 10:12
@Drudoo go back a few revisions -- this is how it worked previously. Shouldn't be hard to find/copypasta the code in for a temporary hack.

**Comment by Drudoo** [comment] 2011-06-01 15:56
I cant find any previous versions on github (i am pretty new to github). Any help would be appreciated. I am looking for the MNAlertDashboardViewController.h and MNAlertDashboardViewController.m

**Comment by exiva** [comment] 2011-06-05 09:18
https://github.com/peterhajas/MobileNotifier/commits/master/MNAlertDashboardViewController.m
https://github.com/peterhajas/MobileNotifier/commits/master/MNAlertDashboardViewController.h

**Comment by Drudoo** [comment] 2011-06-05 09:33
I will take a look later and see if i can find some of the code that works. Right now my own version works, but the problem is that you cant press on the notifications anymore.

**Comment by timnovinger** [comment] 2011-06-06 04:36
This issue was resolved in [this commit](https://github.com/peterhajas/MobileNotifier/commit/90582dee2603ac9c53b9b50ec0b0efd73d30da36).

**Closed as completed by timnovinger** 2011-06-06 04:36 UTC
Labels: Mismatched Functionality, High Priority

**Comment by marshallford** [comment] 2011-06-08 02:55
Now all I need is a mac to compile it...

**Comment by exiva** [comment] 2011-06-08 07:48
I haven't been able to get it to build at all. I think the build directions have changed and the readme hasn't been updated.

**Comment by Drudoo** [comment] 2011-06-08 08:56
This build the same way as every other release :)

**Comment by exiva** [comment] 2011-06-08 08:57
Then I can't setup Theos properly, apparently.

**Comment by Drudoo** [comment] 2011-06-08 09:11
Go in to the Makefile and be sure the first line points to the Theos directory.
