### ISSUE TITLE
Bring back the statusbar preview from beta 4

### ISSUE THREAD

**Issue by joneb** [peterhajas/MobileNotifier#243] opened 2011-05-30 08:10 UTC
Maybe along with a settings toggle.

Lots of great new features in beta 5, but I loved the preview in beta 4, especially for short messages!

**Comment by thecrookedvulture** [comment] 2011-05-30 12:32
I second this, am really missing the preview too!!

**Comment by timbob1907** [comment] 2011-05-30 15:37
Agreed :)

**Comment by TaylorMonkey-duplicate** [comment] 2011-05-30 21:23
Agreed.  A notifier is much less useful when you can't instantly see what it's notifying you about.  I don't know if previews have been removed from all notifications, but this is the case for SMS messages.  I understand that the preview was probably removed so that the message doesn't appear twice when hitting SMS quickreply, but I believe a solution can be found that doesn't sacrifice core functionality (like SMS notification preview).  Here's are two possible fixes:

Show the preview in the notification.  When it is pressed and quick reply is activated, fade the preview out and show the current notificiation with only name and the message in the black dialogue box.

Show the preview in the notification.  When it is pressed, it expands to show the entire message.  Do not display the current dialogue box with the message and just display the quickreply text field and other buttons.

**Comment by btaroli** [comment] 2011-06-01 20:37
Duplicate of #235

I did uninstall MN because of this. Completely useless to me without preview -- no better than just an alert sound, really.

**Comment by timnovinger** [comment] 2011-06-02 05:41
[I've added back](https://github.com/peterhajas/MobileNotifier/commit/7068ed9c193f7c3815bc5372537aa873e0a8f60f) in the notification preview text. Thanks for the feedback everyone.

**Closed as completed by timnovinger** 2011-06-02 05:41 UTC
Labels: Mismatched Functionality, High Priority
