### ISSUE TITLE
FEATURE REQUEST - RETAIN NOTIFICATIONS + MULTIPLE NOTIFICATION + LATER EFFECT

### ISSUE THREAD

**Issue by agentorange29** [peterhajas/MobileNotifier#197] opened 2011-05-18 15:54 UTC
first request : I would like to see the notifications stay either on screen or an option to be able to swipe down/home button gesture and bring the notification bar back. 

second request : Now with the issue of not being able to view multiple notifications unless brought up in the notification screen would make it easier when hitting the later button.

Third request : Effect for the notification with the view later button is pressed. I'm not sure if anyone has seen the effect that tweetbot has when it gives you the option about leaving tweetbot? cancel effect has an effect of dropping down. Would be an awesome effect to see as you are hitting later to go to next notification

by the way the mobile notification rocks!!! keep up the good work developers on this one its definitely a great project

**Comment by mamoc** [comment] 2011-05-19 11:39
first request please!!!

**Comment by JoeyP** [comment] 2011-05-19 19:20
Please do the first request! I might have made a duplicate of it a couple days ago lol.

Also, if it didn't just show 1 notification, but ALL pending notifications that would be the beez neez!

**Closed as completed** 2011-06-06 04:43 UTC
Labels: Outdated Issue
