### ISSUE TITLE
Auto-Correct Quick Reply

### ISSUE THREAD

**Issue by ghost** [peterhajas/MobileNotifier#275] opened 2011-06-03 20:02 UTC
I can't see the auto-correct suggestion when I'm using quick-reply. Maybe u can fix this to show?

**Comment by timnovinger** [comment] 2011-06-03 20:54
Please attach a link to a screenshot of this behavior, thanks!

Sent from my iPhone

On Jun 3, 2011, at 16:02, ymarcus
reply@reply.github.com
wrote:

**Comment by ghost** [comment] 2011-06-03 21:07
Go to this link:
https://picasaweb.google.com/110490759471613641606/ErrorsMobileNotifier?authkey=Gv1sRgCN3vhs-0pNWXCw#5614102802116083618

**Comment by exiva** [comment] 2011-06-03 22:20
Duplicate of https://github.com/peterhajas/MobileNotifier/issues/230

**Comment by timnovinger** [comment] 2011-06-03 22:22
Thanks for the bug report @ymarcus and @exiva!

**Closed as completed** 2011-06-03 22:22 UTC
Labels: Tweak Conflicts, High Priority
