### ISSUE TITLE
Beta 4 not working with BiteSMS

### ISSUE THREAD

**Issue by jonkjon** [peterhajas/MobileNotifier#193] opened 2011-05-18 00:20 UTC
Trying out the latest beta 4 and notifications do not work at all for me on the homescreen. I am running 4.2.1 on cdma iphone.

**Comment by jonkjon** [comment] 2011-05-18 00:39
Discovered scalamanderr's earlier post and found that you need to have biteSMS set to Show Apple Alert in unlock screen mode. I am having the same issue as he was, however, in that selecting the message notification takes you to the messages app and not the biteSMS app as desired.

Additionally, discovered that I am also not receiving mail notifications via MN.

**Comment by caseysprague** [comment] 2011-05-18 18:09
It would be great if that could be fixed. Or perhaps it would be great if MobileNotifier biteSMS notifications could launch the QuickReply.

If you are interested, you can contact the biteSMS dev at help@bitesms.com with the subject "NOT FAQ MARTIN."

Keep up the good work!

**Comment by peterhajas** [comment] 2011-05-18 18:19
This is a duplicate of this issue - https://github.com/peterhajas/MobileNotifier/issues/100

**Closed as completed by peterhajas** 2011-05-18 18:19 UTC
