### ISSUE TITLE
Any way possible to bring text preview to the popup?

### ISSUE THREAD

**Issue by ghost** [peterhajas/MobileNotifier#235] opened 2011-05-29 21:06 UTC
in Beta 4, you could see under the name of the sender, a little msg preview before clicking on the popup! anyway you can bring that back, were you can see a little of the text, and once you click on the popup, you will be able to see full text and mobilereply? Please bring that back, it is more appealing than just getting a popup with a name and app icon on it

**Comment by timaerz** [comment] 2011-05-30 20:57
+1 on that idea.
i miss the preview too!

**Comment by btaroli** [comment] 2011-06-01 20:36
+1 This change has made pop-ups almost completely useless for me. I _did_ uninstall MN because of this.

**Comment by timnovinger** [comment] 2011-06-02 05:42
This issue is a duplicate of [#243](https://github.com/peterhajas/MobileNotifier/issues/243) which is now closed as a result of [this commit](https://github.com/peterhajas/MobileNotifier/commit/7068ed9c193f7c3815bc5372537aa873e0a8f60f).

**Closed as completed by timnovinger** 2011-06-02 05:42 UTC
Labels: Mismatched Functionality, High Priority
