### ISSUE TITLE
Landscape Notifications and AlertDashboard

### ISSUE THREAD

**Issue by undeadrevo** [peterhajas/MobileNotifier#58] opened 2011-03-03 20:57 UTC
Yeah, the title pretty much states my suggestion. The redux of Push Notifications is awesome, and these additions would make it even better.

**Comment by peterhajas** [comment] 2011-03-04 09:33
Thanks for submitting an issue!

It's a duplicate of #7 - https://github.com/peterhajas/MobileNotifier/issues#issue/7 - so I'll close this.

**Closed as completed by peterhajas** 2011-03-04 09:33 UTC
