### ISSUE TITLE
[Enhancement] Mark SMS as read

### ISSUE THREAD

**Issue by exiva** [peterhajas/MobileNotifier#237] opened 2011-05-30 00:09 UTC
My expectation for replying to an SMS via quickreply is to have the SMS I'm replying to marked as read, so there's no more pending # on the SMS app. This does not happen, and is something I'd like to see in a future release of MN. Of course if it's not a iOS limitation.

**Comment by peterhajas** [comment] 2011-05-30 05:57
This is a duplicate of this issue, please move discussion to that page: https://github.com/peterhajas/MobileNotifier/issues/233

**Closed as completed by peterhajas** 2011-05-30 05:57 UTC
